# Generated by Django 5.2.7 on 2025-11-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ideal_answer',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='options_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
