# Generated by Django 5.2.7 on 2025-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_ideal_answer_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='feedback',
        ),
    ]
